server:
  port: 4444
  servlet:
    context-path: /transaction
 
spring:
  boot:
    admin:
      client:
        url: http://adminserver-container
        instance:
          prefer-ip: true
  application:
    name: BankApp-TransactionService
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://transactiondb-docker-container/bankApp-Transaction-Command-DB?createDatabaseIfNotExist=true
    username: root
    password: root
 
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
       hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
                                      
eureka:
  client:
    service-url : 
            defaultZone: http://eurekaservice-container/eureka/          
            
    register-with-eureka: true
    fetch-registry: true 
 
  instance:
    prefer-ip-address: true
    
axon:
  eventhandling:
    processors:
      name:
        mode: tracking
        
  distributed:
    enabled: true
  
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

 