server:
  port: 2222
  servlet:
    context-path: "/customer"
 
spring:
  boot:
    admin:
      client:
        url: http://adminserver-container
        instance:
          prefer-ip: true
  application:
    name: BankApp-CustomerService
    
  datasource:
    url: jdbc:mysql://customerdb-docker-container/bankApp-Customer-Command-DB?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
 
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
       hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
                                      
eureka:
  client:
    service-url : 
            defaultZone: http://eurekaservice-container/eureka/          
            
    register-with-eureka: true
    fetch-registry: true 
 
  instance:
    prefer-ip-address: true
    
axon:
  eventhandling:
    processors:
      name:
        mode: tracking
        
  distributed:
    enabled: true
    
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
        

 